#!/bin/bash

set -euo pipefail

default_password_length=43

password_length=${1:-$default_password_length} # default to just over 256 bits

if ! [[ $password_length =~ ^[0-9]+$ && $password_length -gt 0 ]]; then
	echo "$(basename "$0"): password length must be a positive integer" 1>&2
	exit 1
fi

random_password=$( (tr -dc '[:alnum:]' || true) </dev/urandom \
			| head -c"${password_length}")

echo "${random_password}"
