#!/bin/bash

set -euo pipefail
set -x

main() {
        run_test_functions
}

run_test_functions() {
        for test_function in $(compgen -A function test_); do
                "$test_function"
        done
}

test_shellcheck_script() {
	shellcheck randompassword
}

test_default_password() {
	randompassword | grep -q '^[a-zA-Z0-9]\{43\}$'
}

test_12char_password() {
	randompassword 12 | grep -q '^[a-zA-Z0-9]\{12\}$'
}

test_argument_parsing() {
	local error_message="$(! randompassword not_a_number 2>&1)"
	echo "$error_message" | grep -q 'randompassword: password length must be a positive integer'
}

main
