name: Test randompassword
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '23 6 * * 1'
jobs:
  test-randompassword:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck test_randompassword
      - run: bash test_randompassword
